FROM python:3.12-slim

# Use a different mirror
RUN sed -i 's/deb.debian.org/ftp.us.debian.org/g' /etc/apt/sources.list.d/debian.sources || \
    sed -i 's/deb.debian.org/ftp.us.debian.org/g' /etc/apt/sources.list

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    make \
    curl \
    default-jdk \
    php \
    nodejs \
    golang \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash judge

WORKDIR /app

COPY . .

ENV PATH="/root/.local/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

ENV PYTHONUNBUFFERED=1
ENV TLE_TIMEOUT=30

RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --install-dir /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

ENV PATH="/usr/share/dotnet:$PATH"
RUN dotnet tool install -g dotnet-script

RUN chown -R judge:judge /app

USER judge

ENV PATH="/root/.dotnet/tools:/home/judge/.dotnet/tools:/usr/share/dotnet:$PATH:/root/.local/bin"

CMD ["python", "-m", "src.main"]